### ISSUE TITLE
Typo in VTF Embed Description

### ISSUE THREAD

**Issue by MarkKoz** [tophattwaffle/BotHATTwaffle#1]
Command: `>vtf`

> VTFEdit is a lightweight program that can be used to convert images into the Valve VTF image format. It is much easier to use than VTEX.exe and provides a nice GUI for **everythign** you'd ever need to get your images into the Source Engine

everythign -> everything

The last sentence is also missing a full stop.

**Comment by tophattwaffle** [comment]
Fixed.
