### ISSUE TITLE
Providing too few parameters displays that you provided too many

### ISSUE THREAD

**Issue by tophattwaffle** [tophattwaffle/BotHATTwaffle#17]
![discord_2018-02-01_18-11-25](https://user-images.githubusercontent.com/6774125/35712230-a79a3854-0786-11e8-8fc2-9a457182f9eb.png)

**Comment by MarkKoz** [comment]
Cannot reproduce. `rcon` and `pc` used to have issues, which I have fixed already. Are you running an older build?

**Comment by tophattwaffle** [comment]
Looks like this may have been from a previous build, my bad.
