### ISSUE TITLE
Handling Schema Discrepancies 

### ISSUE THREAD

**Issue by MarkKoz** [tophattwaffle/BotHATTwaffle#20]
A way of solving discrepancies would be to commit the migrations. First, this would allow for tracking the history of changes to the schema without having to revert to older commits. 

More importantly, it allows keeping the local database in sync with the EF model while also preserving data. It would become the responsibility of the commit's author to modify the migration accordingly to copy data over when: 

- Dropping tables
- Dropping columns
- Adding required columns to existing tables
- Renaming
- Et cetera

**Comment by tophattwaffle** [comment]
Will the "Migration" then handle updating/creating the database as needed if not exists?

**Comment by MarkKoz** [comment]
Yes. When you create the migration, it generates a file with a class that inherits `Microsoft.EntityFrameworkCore.Migrations.Migration`. You can go over it and add any changes as needed to preserve data (the generated migration won't do this part for you). Once changes are made, it can be applied to the local database.

Read [this](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/#adding-another-migration) for more info. There's also a section on use in team environments which I recommend looking over.

**Comment by MarkKoz** [comment]
Started using migrations in ab7d46f.
